export {default as Header} from './Header';
export {default as Categories} from './Categories';
export {default as Sorting} from './Sorting';
export {default as AppliedFilters} from './AppliedFilters';
export {default as Sidebar} from './Sidebar';
export {default as Catalog} from './Catalog';
export {default as Cart} from './Cart';
export {default as Login} from './Login';
export {default as Register} from './Register';